const express=require('express');const {userFromRequest}=require('../../../lib/supabase');const {ensureDailyReset}=require('../../../lib/credits');const {getSiteSettings}=require('../../../lib/site-settings');const router=express.Router()
async function admin(req,res){const x=await userFromRequest(req);if(x.error)return{res:res.status(401).json({success:false,message:x.error})};await ensureDailyReset();const {data,error}=await x.sb.from('profiles').select('role').eq('id',x.user.id).single();if(error||data?.role!=='admin')return{res:res.status(403).json({success:false,message:'Akses pengelola diperlukan.'})};return x}
router.get('/overview',async(req,res)=>{try{const x=await admin(req,res);if(x.res)return;await ensureDailyReset();const [{data:users,error:uerr},{data:settings,error:serr}]=await Promise.all([x.sb.from('profiles').select('id,email,display_name,role,credits,daily_credits,created_at,updated_at'),x.sb.from('site_settings').select('*').eq('id',1).single()]);if(uerr)throw uerr;if(serr)throw serr;const total=users.length,admins=users.filter(u=>u.role==='admin').length,totalCredits=users.reduce((n,u)=>n+(Number(u.credits)||0),0);res.json({success:true,stats:{totalUsers:total,adminCount:admins,userCount:total-admins,totalCredits,maintenance:!!settings.maintenance,broadcast:!!settings.broadcast_active},settings});}catch(e){res.status(500).json({success:false,message:e.message})}})
router.get('/users',async(req,res)=>{try{const x=await admin(req,res);if(x.res)return;const {data,error}=await x.sb.from('profiles').select('id,email,display_name,role,credits,daily_credits,credit_reset_at').order('email');if(error)throw error;res.json({success:true,users:data})}catch(e){res.status(500).json({success:false,message:e.message})}})
router.post('/credits',async(req,res)=>{try{const x=await admin(req,res);if(x.res)return;const userId=String(req.body.userId||'');const amount=Number(req.body.amount);if(!userId||!Number.isInteger(amount)||amount===0)return res.status(400).json({success:false,message:'ID pengguna dan jumlah kredit wajib diisi.'});const {data,error}=await x.sb.rpc('admin_adjust_credit',{p_admin_id:x.user.id,p_user_id:userId,p_amount:amount});if(error)throw error;res.json({success:true,profile:data})}catch(e){res.status(400).json({success:false,message:e.message})}})
router.post('/daily-credits',async(req,res)=>{try{const x=await admin(req,res);if(x.res)return;const userId=String(req.body.userId||'');const amount=Number(req.body.dailyCredits);if(!userId||!Number.isInteger(amount)||amount<0||amount>100000)return res.status(400).json({success:false,message:'ID pengguna dan kredit harian tidak valid.'});const {data,error}=await x.sb.from('profiles').update({daily_credits:amount,updated_at:new Date().toISOString()}).eq('id',userId).select('id,email,credits,daily_credits').single();if(error)throw error;res.json({success:true,profile:data})}catch(e){res.status(400).json({success:false,message:e.message})}})
router.get('/settings',async(req,res)=>{try{const x=await admin(req,res);if(x.res)return;res.json({success:true,settings:await getSiteSettings()})}catch(e){res.status(500).json({success:false,message:e.message})}})
router.post('/settings',async(req,res)=>{try{const x=await admin(req,res);if(x.res)return;const patch={};if(typeof req.body.maintenance==='boolean')patch.maintenance=req.body.maintenance;if(typeof req.body.maintenance_message==='string')patch.maintenance_message=req.body.maintenance_message.trim().slice(0,500);if(typeof req.body.broadcast_active==='boolean')patch.broadcast_active=req.body.broadcast_active;if(typeof req.body.broadcast_title==='string')patch.broadcast_title=req.body.broadcast_title.trim().slice(0,120);if(typeof req.body.broadcast_message==='string')patch.broadcast_message=req.body.broadcast_message.trim().slice(0,2000);if(req.body.new_broadcast===true){patch.broadcast_id=cryptoRandomId()}const {data,error}=await x.sb.from('site_settings').update(patch).eq('id',1).select('*').single();if(error)throw error;res.json({success:true,settings:data})}catch(e){res.status(400).json({success:false,message:e.message})}})
function cryptoRandomId(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)}
module.exports=router
